language: cpp
compiler:
  - gcc
  - clang
  - cmake

before_script:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update
  - sudo apt-get install libpcl-all
# Change this to your needs
script: cmake . && make
